# Generated by Django 5.2.7 on 2025-10-07 14:07

from django.db import migrations, models
from django.utils import timezone   # <-- AÑADIDO

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='compania',
            field=models.CharField(default='sin definir', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='correo',
            field=models.EmailField(default='sin_correo@empresa.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_creacion',
            # Usa timezone.now SOLO para rellenar filas existentes al aplicar la migración.
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='pais',
            field=models.CharField(default='Sin pais', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='Sin telefono', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
