# Generated by Django 5.2.7 on 2025-10-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_empresa_descripcion_empresa_compania_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre',
            new_name='cliente',
        ),
    ]
